version: '3.8'
services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    #hostname: namenode
    #extra_hosts:
      #- "namenode:172.19.0.2"
    environment:
      CLUSTER_NAME: datapipeline
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ../hadoop/conf:/etc/hadoop/conf
    

  datanode:
    image: bde2020/hadoop-datanode:latest
    depends_on:
      - namenode
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ../hadoop/conf:/etc/hadoop/conf
    

  hive-metastore:
    image: bde2020/hive-metastore-postgresql:latest
    environment:
      # Force using PostgreSQL metastore
      HIVE_METASTORE_URIS: "thrift://hive-metastore:9083"
      METASTORE_DB_TYPE: "postgres"
      METASTORE_DB_HOST: "hive-metastore"
      METASTORE_DB_PORT: "5432"
      METASTORE_DB_NAME: "metastore"
      METASTORE_DB_USER: "postgres"
      METASTORE_DB_PASS: "postgres"
      SKIP_SCHEMA_INIT: "true"

      SERVICE_NAME: metastore
      DB_TYPE: postgres
      DB_HOST: hive-metastore
      DB_PORT: 5432
      DB_NAME: hive_metastore
      DB_USER: postgres  
      DB_PASS: postgres  
      METASTORE_PORT: 9083
    ports:
      - "9083:9083"
    command: >
      bash -c "
      # Initialize PostgreSQL if needed
      if [ ! -f /var/lib/postgresql/data/PG_VERSION ]; then
        /docker-entrypoint.sh postgres
      fi
      
      # Start PostgreSQL
      docker-entrypoint.sh postgres &
      
      # Wait for PostgreSQL to be fully ready
      while ! pg_isready -U postgres -h localhost -q; do 
        sleep 1
      done
      
      # Initialize metastore schema if needed
      if [ ! -f /opt/hive/metastore_schema_initialized ]; then
        /opt/hive/bin/schematool -dbType postgres -initSchema
        touch /opt/hive/metastore_schema_initialized
      fi
      
      # Start metastore service (keeps container running)
      exec /opt/hive/bin/hive --service metastore
      "
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep 9083 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    

  hive-server:
    #image: bde2020/hive:latest
    image: apache/hive:4.0.0-beta-1
    #hostname: hive-server
    environment:
      SERVICE_NAME: hiveserver2
      HIVE_METASTORE_URIS: "thrift://hive-metastore:9083"
      METASTORE_DB_TYPE: "postgres"
      METASTORE_DB_HOST: "hive-metastore"
      METASTORE_DB_PORT: "5432"
      METASTORE_DB_NAME: "metastore"
      METASTORE_DB_USER: "postgres"
      METASTORE_DB_PASS: "postgres"
      SKIP_SCHEMA_INIT: "true"
      #HIVE_METASTORE_HOST: hive-metastore
      #HIVE_METASTORE_PORT: 9083
      HIVE_CATALOG_METASTORE: true
      HIVE_SERVER2_THRIFT_PORT: 10000
      HIVE_SERVER2_THRIFT_BIND_HOST: 0.0.0.0
      HIVE_SERVER2_AUTHENTICATION: NOSASL
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
      HIVE_METASTORE_SCHEMA_VERIFICATION: "false"
      HIVE_SERVER2_USE_NAMENODE_URI: "true"
      #HIVE_HADOOP_CLASSPATH: /opt/hadoop-2.7.4/etc/hadoop:/opt/hadoop-2.7.4/share/hadoop/common/lib/*:/opt/hadoop-2.7.4/share/hadoop/common/*:/opt/hadoop-2.7.4/share/hadoop/hdfs/*:/opt/hadoop-2.7.4/share/hadoop/hdfs/lib/*:/opt/hadoop-2.7.4/share/hadoop/yarn/lib/*:/opt/hadoop-2.7.4/share/hadoop/yarn/*:/opt/hadoop-2.7.4/share/hadoop/mapreduce/lib/*:/opt/hadoop-2.7.4/share/hadoop/mapreduce/*
    volumes:
      - ../hadoop/conf:/etc/hadoop/conf
      - hive-logs:/opt/hive/logs
      - ./postgresql-42.6.0.jar:/opt/hive/lib/postgresql.jar
      - ./postgresql-42.6.0.jar:/usr/share/java/kafka-connect-jdbc/postgresql.jar
    ports:
      - "10000:10000"
      - "10002:10002"
    command: >
      bash -c "
      /opt/hive/bin/hiveserver2 
      --hiveconf hive.metastore.uris=thrift://hive-metastore:9083
      --hiveconf javax.jdo.option.ConnectionURL=jdbc:postgresql://hive-metastore:5432/metastore
      --hiveconf javax.jdo.option.ConnectionDriverName=org.postgresql.Driver
      --hiveconf javax.jdo.option.ConnectionUserName=postgres
      --hiveconf javax.jdo.option.ConnectionPassword=postgres
      "
    depends_on:
      - hive-metastore
      - namenode
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep 10000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  datapipeline-net:
    external: true
    name: datapipeline-net
    driver: bridge


volumes:
  hadoop_namenode:
  hadoop_datanode:
  hive-logs: