version: '3.8'
services:
  connect:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8083:8083"
    environment:
      KAFKA_OPTS: "-Dsun.net.inetaddr.ttl=0 -Dsun.net.inetaddr.negative.ttl=0"
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_GROUP_ID: connect-cluster
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-statuses
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_HEAP_OPTS: "-Xms512m -Xmx1024m"
    volumes:
      - ../hadoop/conf:/etc/hadoop/conf
      - ./postgresql-42.6.0.jar:/opt/hive/lib/postgresql.jar
      - ./postgresql-42.6.0.jar:/usr/share/java/kafka-connect-jdbc/postgresql.jar

networks:
  datapipeline-net:
    name: datapipeline-net
    driver: bridge