#version: '3.8'
services:
  postgres-airflow:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres-airflow-data:/var/lib/postgresql/data

  airflow-scheduler:
    #image: apache/airflow:2.3.0
    image: apache/airflow:2.7.3
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      #- AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflow_example_key
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS=False
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
    depends_on:
      - postgres-airflow
    restart: unless-stopped

  airflow-webserver:
    #image: apache/airflow:2.3.0
    image: apache/airflow:2.7.3
    command: webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      #- AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflow_example_key
      - AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS=False
    ports:
      - "8080:8080"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
    depends_on:
      - postgres-airflow
      - airflow-scheduler
    restart: unless-stopped

volumes:
  postgres-airflow-data: