version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      POSTGRES_MULTIPLE_DATABASES: "mydb,hive_metastore"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-hive.sql:/docker-entrypoint-initdb.d/init-hive.sql
    command: ["postgres", "-c", "wal_level=logical"]
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U postgres && psql -U postgres -d mydb -c 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  postgres-data:

networks:
  datapipeline-net:
    name: datapipeline-net
    driver: bridge