FROM python:3.8-slim

RUN apt-get update && apt-get install -y postgresql-client

WORKDIR /app

COPY ../scripts/crypto_ingest.py /app/
COPY ../scripts/test_generator.py /app/

RUN pip install psycopg2-binary requests

CMD ["python", "/app/crypto_ingest.py"]