version: '3.8'
services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    hostname: namenode
    extra_hosts:
      - "namenode:172.19.0.2"
    environment:
      - CLUSTER_NAME=datapipeline
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ../hadoop/conf:/etc/hadoop/conf
    networks:
      - hadoop-net

  datanode:
    image: bde2020/hadoop-datanode:latest
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ../hadoop/conf:/etc/hadoop/conf
    networks:
      - hadoop-net

  hive-metastore:
    image: bde2020/hive-metastore-postgresql:latest
    environment:
      - DB_TYPE=postgres
      - DB_DRIVER=postgresql
      - DB_USER=hive
      - DB_PASS=hive
      - DB_HOST=postgres-airflow
      - DB_PORT=5432
      - DB_NAME=hive_metastore
    ports:
      - "9083:9083"
    depends_on:
      - namenode
    networks:
      - hadoop-net

  hive-server:
    image: bde2020/hive:latest
  hostname: hive-server
  environment:
    - SERVICE_NAME=hiveserver2
    - HIVE_METASTORE_HOST=hive-metastore
    - HIVE_METASTORE_PORT=9083
    - HIVE_SERVER2_THRIFT_PORT=10000
    - HIVE_SERVER2_THRIFT_BIND_HOST=0.0.0.0
    - HIVE_SERVER2_AUTHENTICATION=NOSASL
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - HIVE_HADOOP_CLASSPATH=/opt/hadoop-2.7.4/etc/hadoop:/opt/hadoop-2.7.4/share/hadoop/common/lib/*:/opt/hadoop-2.7.4/share/hadoop/common/*:/opt/hadoop-2.7.4/share/hadoop/hdfs/*:/opt/hadoop-2.7.4/share/hadoop/hdfs/lib/*:/opt/hadoop-2.7.4/share/hadoop/yarn/lib/*:/opt/hadoop-2.7.4/share/hadoop/yarn/*:/opt/hadoop-2.7.4/share/hadoop/mapreduce/lib/*:/opt/hadoop-2.7.4/share/hadoop/mapreduce/*
  volumes:
    - ../hadoop/conf:/etc/hadoop/conf
    - hive-logs:/opt/hive/logs
  ports:
    - "10000:10000"
    - "10002:10002"
  command: >
    bash -c "
    mkdir -p /opt/hive/logs &&
    /opt/hive/bin/hiveserver2 --hiveconf hive.root.logger=INFO,console &
    tail -f /dev/null
    "
  depends_on:
    - hive-metastore
    - namenode
  networks:
    - hadoop-net

networks:
  hadoop-net:
    driver: bridge


volumes:
  hadoop_namenode:
  hadoop_datanode:
  hive-logs: